name: Deploy-functiongraph-sample1

on:
  push:
    branches: 
    - 'master'
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0.4

      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
        project_id: ${{ secrets.PROJECT_ID }}
        function_codetype: jar
        function_urn: urn:fss:cn-north-4:${{ secrets.PROJECT_ID }}:function:default:github-action-sample-jar:latest
        function_file: ./java-sample/functionj.jar
